<?php
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ck_form_handler_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  unset($form['name']['#description'], $form['pass']['#description']);
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_ck_form_handler_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _ck_form_handler_user_login_form_submit($form, FormStateInterface $form_state) {
  $errors = $form_state->getErrors();
  if (!$errors) {
    global $base_url;
    $redirect = new RedirectResponse($base_url . '/admin');
    $redirect->send();
  }
}
