name: 'Sitemap additional settings'
type: module
description: 'Additional settings for sitemap module to generate relevant list'

version: '8.x-0.1'
core: '8.x'
project: 'sitemap_additional_settings'
datestamp: 1585661549
