services:
  sitemap_additional_settings.breadcrumb_sitemap_additional_settings:
    class: Drupal\sitemap_additional_settings\Breadcrumb\SitemapAdditionalSettingsBreadcrumbBuilder
    arguments: ['@router.request_context', '@access_manager', '@router', '@path_processor_manager', '@config.factory',  '@title_resolver', '@current_user', '@path.current', '@path.matcher']
    tags:
      - { name: breadcrumb_builder, priority: 1002 }
