<?php

function sitemap_additional_settings_cron() {
  $iteration_start_time = time();
  $last_start = \Drupal::state()
    ->get('sitemap_additional_settings.last_start', 0);

  if ($iteration_start_time - $last_start > 79200) { // 22 часа
    $entities = \Drupal::state()
      ->get('sitemap_additional_settings.entities', []);
    if (!$entities) {
      \Drupal::state()->set('map_levels', []);
      $entities_temp = \Drupal::service('sitemap_additional_settings.get_entities_items')
        ->getEntitiesItems();
      foreach ($entities_temp as $entitie_item) {
        $entities = array_merge($entities, $entitie_item);
      }
      $entities[] = 'finish';
    }
    $processed_entities_count = 0;
    foreach ($entities as $entity) {
      if (time() - $iteration_start_time >= 20) {
        break;
      }
      if ($entity === 'finish') {
        $processed_entities_count++;
        break;
      }
      \Drupal::service('sitemap_additional_settings.process_items')
        ->processItem($entity);
      $processed_entities_count++;
    }

    $entities = array_slice($entities, $processed_entities_count);
    \Drupal::state()
      ->set('sitemap_additional_settings.entities', $entities);

    if (!$entities) {
      \Drupal::service('sitemap_additional_settings.refill_site_map_menu')
        ->refillSiteMapMenu();
      \Drupal::state()
        ->set('sitemap_additional_settings.last_start', $iteration_start_time);
    }
  }
}
