<?php
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

function schedule_field_theme($existing, $type, $theme, $path) {
  $variables = array(
    'schedule' => array (
      'render element' => 'element',
      'template' => 'schedule-input',
    ),
  );
  return $variables;
}

function schedule_field_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'doctors' && $view->current_display == 'page_1') {
    $a = 1;
  }
  $a = 1;
}