<?php
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

function schedule_field_theme($existing, $type, $theme, $path) {
  $variables = array(
    'schedule' => array (
      'render element' => 'element',
      'template' => 'schedule-input',
    ),
  );
  return $variables;
}

/**
 * Вмешиваемся в работу отображения страницы списка докторов, чтобы обеспечить
 * фильтрацию докторов по клинике на основе поля "График работы"
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param \Drupal\views\Plugin\views\query\QueryPluginBase $query
 */
function schedule_field_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'doctors' && $view->current_display == 'page_1') {
    $query->addWhere(count($query->where), 'node_field_data.nid', 219, '=');
    $a = 1;
  }
}