<?php

/**
 *  Implements hook_cron()
 */
function tilda_export_cron() {
  /** @var \Drupal\tilda_export\TildaExportProcess $tildaExportProcess*/
  $tildaExportProcess = \Drupal::service('tilda_export_process');
  $tildaExportProcess->exportPageFromTilda();
}

/**
 * Implements hook_page_attachments().
 */
function tilda_export_page_attachments(array &$attachments) {
  /** @var \Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'tilda_export/tilda';
  }
}